name: Check compatibility step 2

on:
  workflow_run:
    workflows: [ "Check compatibility step 1" ]
    types:
      - completed

jobs:
  commenting-job:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
    steps:
      - name: â¬‡ï¸ Download compatibility report and PR number
        uses: actions/download-artifact@v4
        with:
          run-id: ${{github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ hashFiles('pr_number.txt') != '' }}
        name: âš™ï¸ Load PR number
        id: pr_number
        run: echo "number=$(cat pr_number.txt)" >> $GITHUB_OUTPUT

      - if: ${{ hashFiles('pr_number.txt') != '' }}
        name: ðŸ”” Notify PR with compatibility report
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.pr_number.outputs.number }}
          body-path: 'compatibility.md'
